In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = (18,12)

from ipywidgets import interact, IntSlider, FloatSlider

In [2]:
df_sample = pd.read_csv('sample_submission.csv', sep=',', encoding='utf8')

In [3]:
df_sample.head()

_id  target
0  66810d8e6bf2b41c880a7bc6c8a1e295       0
1  ccac3879652b08cb8b44c1920fd93afa       0
2  fcccab4d7a76f70647f015f2c84c2af8       0
3  ed8399278c30678dab739045fa12b440       0
4  1d4d62ac5cabcb48bac7112813f290cb       0

In [4]:
df_test = pd.read_csv('test.csv', sep=',', encoding='utf8')

In [5]:
df_test.head()

_id  age          job  marital    education  \
0  66810d8e6bf2b41c880a7bc6c8a1e295   57   technician  married  high.school   
1  ccac3879652b08cb8b44c1920fd93afa   55      unknown  married      unknown   
2  fcccab4d7a76f70647f015f2c84c2af8   33  blue-collar  married     basic.9y   
3  ed8399278c30678dab739045fa12b440   36       admin.  married  high.school   
4  1d4d62ac5cabcb48bac7112813f290cb   27    housemaid  married  high.school   

   default housing loan    contact month     ...      duration  campaign  \
0       no      no  yes   cellular   may     ...           371         1   
1  unknown     yes   no  telephone   may     ...           285         2   
2       no      no   no   cellular   may     ...            52         1   
3       no      no   no  telephone   jun     ...           355         4   
4       no     yes   no   cellular   jul     ...           189         2   

   pdays  previous     poutcome emp.var.rate  cons.price.idx  cons.conf.idx  \
0    999         1      failure         -1.8          92.893          -46.2   
1    999         0  nonexistent          1.1          93.994          -36.4   
2    999         1      failure         -1.8          92.893          -46.2   
3    999         0  nonexistent          1.4          94.465          -41.8   
4    999         0  nonexistent          1.4          93.918          -42.7   

   euribor3m  nr.employed  
0      1.299       5099.1  
1      4.860       5191.0  
2      1.313       5099.1  
3      4.967       5228.1  
4      4.963       5228.1  

[5 rows x 21 columns]

In [6]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16476 entries, 0 to 16475
Data columns (total 21 columns):
_id               16476 non-null object
age               16476 non-null int64
job               16476 non-null object
marital           16476 non-null object
education         16476 non-null object
default           16476 non-null object
housing           16476 non-null object
loan              16476 non-null object
contact           16476 non-null object
month             16476 non-null object
day_of_week       16476 non-null object
duration          16476 non-null int64
campaign          16476 non-null int64
pdays             16476 non-null int64
previous          16476 non-null int64
poutcome          16476 non-null object
emp.var.rate      16476 non-null float64
cons.price.idx    16476 non-null float64
cons.conf.idx     16476 non-null float64
euribor3m         16476 non-null float64
nr.employed       16476 non-null float64
dtypes: float64(5), int64(5), object(11)
memory usa

In [7]:
df_train = pd.read_csv('train.csv', sep=',', encoding='utf8')

In [8]:
df_train.head()

_id  age          job  marital  \
0  df7489733b004bbe40d3d37b34f82419   54   technician  married   
1  905a0b9a5456ee962223033473666be3   36     services   single   
2  02d69c07ec6d68e31d641edd45ce61cd   53  blue-collar  married   
3  e492fbe0cccaf67cdb5c0944dbc8a167   34  blue-collar  married   
4  ac2dc6f5835bdea8e71dd99b65208d07   29     services   single   

             education  default housing loan    contact month   ...    \
0  professional.course  unknown      no   no   cellular   aug   ...     
1             basic.4y       no      no   no  telephone   may   ...     
2             basic.4y       no     yes   no   cellular   aug   ...     
3             basic.9y       no     yes  yes  telephone   may   ...     
4    university.degree       no     yes   no  telephone   aug   ...     

  campaign  pdays  previous     poutcome  emp.var.rate cons.price.idx  \
0        1    999         0  nonexistent           1.4         93.444   
1        1    999         0  nonexistent           1.1         93.994   
2        1    999         0  nonexistent           1.4         93.444   
3        2    999         0  nonexistent           1.1         93.994   
4        1    999         0  nonexistent          -1.7         94.027   

   cons.conf.idx  euribor3m  nr.employed  target  
0          -36.1      4.963       5228.1       0  
1          -36.4      4.857       5191.0       0  
2          -36.1      4.965       5228.1       0  
3          -36.4      4.857       5191.0       0  
4          -38.3      0.890       4991.6       0  

[5 rows x 22 columns]

In [9]:
df_train.shape

(24712, 22)

In [10]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24712 entries, 0 to 24711
Data columns (total 22 columns):
_id               24712 non-null object
age               24712 non-null int64
job               24712 non-null object
marital           24712 non-null object
education         24712 non-null object
default           24712 non-null object
housing           24712 non-null object
loan              24712 non-null object
contact           24712 non-null object
month             24712 non-null object
day_of_week       24712 non-null object
duration          24712 non-null int64
campaign          24712 non-null int64
pdays             24712 non-null int64
previous          24712 non-null int64
poutcome          24712 non-null object
emp.var.rate      24712 non-null float64
cons.price.idx    24712 non-null float64
cons.conf.idx     24712 non-null float64
euribor3m         24712 non-null float64
nr.employed       24712 non-null float64
target            24712 non-null int64
dtypes: floa

In [11]:
y_target_id = df_train.loc[:,['_id','target']]

In [12]:
y_target_id.head()

_id  target
0  df7489733b004bbe40d3d37b34f82419       0
1  905a0b9a5456ee962223033473666be3       0
2  02d69c07ec6d68e31d641edd45ce61cd       0
3  e492fbe0cccaf67cdb5c0944dbc8a167       0
4  ac2dc6f5835bdea8e71dd99b65208d07       0

In [13]:
y_target = df_train.iloc[:, -1].values

In [14]:
y_target[:40]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [15]:
df_train = df_train.drop(['_id','target'], axis=1).copy()

In [16]:
cat_cols = []
for col in df_train.columns: # перебираем все столбцы
    if (str(df_train[col].dtype) == 'object'): # если тип столбца - object
        cat_cols.append(col)
cat_cols

['job',
 'marital',
 'education',
 'default',
 'housing',
 'loan',
 'contact',
 'month',
 'day_of_week',
 'poutcome']

In [17]:
df_train = pd.get_dummies(df_train, columns=cat_cols)

In [18]:
df_train.shape

(24712, 63)

In [19]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24712 entries, 0 to 24711
Data columns (total 63 columns):
age                              24712 non-null int64
duration                         24712 non-null int64
campaign                         24712 non-null int64
pdays                            24712 non-null int64
previous                         24712 non-null int64
emp.var.rate                     24712 non-null float64
cons.price.idx                   24712 non-null float64
cons.conf.idx                    24712 non-null float64
euribor3m                        24712 non-null float64
nr.employed                      24712 non-null float64
job_admin.                       24712 non-null uint8
job_blue-collar                  24712 non-null uint8
job_entrepreneur                 24712 non-null uint8
job_housemaid                    24712 non-null uint8
job_management                   24712 non-null uint8
job_retired                      24712 non-null uint8
job_self-employed

In [20]:
df_y_target = pd.DataFrame(y_target_id['target'], columns=['target'], copy=True)

In [21]:
df_y_target.head(10)

target
0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       1
9       0

In [22]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(df_train, y_target, test_size = 0.3, random_state = 123)

In [24]:
model = Pipeline([
    ('scaler', StandardScaler()),
    ('knn', KNeighborsClassifier(n_neighbors=50))
])

In [25]:
model.fit(X_train, y_train)

Pipeline(memory=None,
     steps=[('scaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('knn', KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=50, p=2,
           weights='uniform'))])

In [26]:
y_hat = model.predict(X_test)

In [27]:
y_hat_proba = model.predict_proba(X_test, )

In [28]:
y_hat_proba[:20]

array([[1.  , 0.  ],
       [0.96, 0.04],
       [0.96, 0.04],
       [0.96, 0.04],
       [0.7 , 0.3 ],
       [0.96, 0.04],
       [0.96, 0.04],
       [0.98, 0.02],
       [0.42, 0.58],
       [0.98, 0.02],
       [0.52, 0.48],
       [0.98, 0.02],
       [0.96, 0.04],
       [0.98, 0.02],
       [0.96, 0.04],
       [0.96, 0.04],
       [0.54, 0.46],
       [0.9 , 0.1 ],
       [0.98, 0.02],
       [0.92, 0.08]])

In [29]:
y_hat_proba.shape

(7414, 2)

In [30]:
from sklearn.metrics import roc_auc_score

In [31]:
roc_auc_score(y_test, y_hat_proba[:, 1])

0.8773530647427819

In [32]:
y_hat[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [33]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16476 entries, 0 to 16475
Data columns (total 21 columns):
_id               16476 non-null object
age               16476 non-null int64
job               16476 non-null object
marital           16476 non-null object
education         16476 non-null object
default           16476 non-null object
housing           16476 non-null object
loan              16476 non-null object
contact           16476 non-null object
month             16476 non-null object
day_of_week       16476 non-null object
duration          16476 non-null int64
campaign          16476 non-null int64
pdays             16476 non-null int64
previous          16476 non-null int64
poutcome          16476 non-null object
emp.var.rate      16476 non-null float64
cons.price.idx    16476 non-null float64
cons.conf.idx     16476 non-null float64
euribor3m         16476 non-null float64
nr.employed       16476 non-null float64
dtypes: float64(5), int64(5), object(11)
memory usa

In [34]:
df_y_test = df_test.loc[:,['_id']]

In [35]:
df_y_test.head()

_id
0  66810d8e6bf2b41c880a7bc6c8a1e295
1  ccac3879652b08cb8b44c1920fd93afa
2  fcccab4d7a76f70647f015f2c84c2af8
3  ed8399278c30678dab739045fa12b440
4  1d4d62ac5cabcb48bac7112813f290cb

In [36]:
df_test = df_test.drop(['_id'], axis=1).copy()

In [37]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16476 entries, 0 to 16475
Data columns (total 20 columns):
age               16476 non-null int64
job               16476 non-null object
marital           16476 non-null object
education         16476 non-null object
default           16476 non-null object
housing           16476 non-null object
loan              16476 non-null object
contact           16476 non-null object
month             16476 non-null object
day_of_week       16476 non-null object
duration          16476 non-null int64
campaign          16476 non-null int64
pdays             16476 non-null int64
previous          16476 non-null int64
poutcome          16476 non-null object
emp.var.rate      16476 non-null float64
cons.price.idx    16476 non-null float64
cons.conf.idx     16476 non-null float64
euribor3m         16476 non-null float64
nr.employed       16476 non-null float64
dtypes: float64(5), int64(5), object(10)
memory usage: 2.5+ MB


In [38]:
cat_cols = []
for col in df_test.columns: # перебираем все столбцы
    if (str(df_test[col].dtype) == 'object'): # если тип столбца - object
        cat_cols.append(col)
cat_cols

['job',
 'marital',
 'education',
 'default',
 'housing',
 'loan',
 'contact',
 'month',
 'day_of_week',
 'poutcome']

In [39]:
df_test = pd.get_dummies(df_test, columns=cat_cols)

In [40]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16476 entries, 0 to 16475
Data columns (total 63 columns):
age                              16476 non-null int64
duration                         16476 non-null int64
campaign                         16476 non-null int64
pdays                            16476 non-null int64
previous                         16476 non-null int64
emp.var.rate                     16476 non-null float64
cons.price.idx                   16476 non-null float64
cons.conf.idx                    16476 non-null float64
euribor3m                        16476 non-null float64
nr.employed                      16476 non-null float64
job_admin.                       16476 non-null uint8
job_blue-collar                  16476 non-null uint8
job_entrepreneur                 16476 non-null uint8
job_housemaid                    16476 non-null uint8
job_management                   16476 non-null uint8
job_retired                      16476 non-null uint8
job_self-employed

In [41]:
y_hat2 = model.predict(df_test)

In [42]:
y_hat_proba2 = model.predict_proba(df_test, )

In [43]:
y_hat_proba2[:20]

array([[0.94, 0.06],
       [0.98, 0.02],
       [0.98, 0.02],
       [0.98, 0.02],
       [1.  , 0.  ],
       [0.92, 0.08],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.98, 0.02],
       [0.94, 0.06],
       [0.92, 0.08],
       [0.9 , 0.1 ],
       [0.88, 0.12],
       [0.88, 0.12],
       [0.92, 0.08],
       [0.98, 0.02],
       [0.96, 0.04],
       [0.88, 0.12],
       [0.94, 0.06],
       [0.82, 0.18]])

In [44]:
y_hat2[40:]

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [45]:
df_result = df_y_test.copy()

In [46]:
df_y_hat2 = pd.DataFrame(y_hat2, columns=['target'])

In [47]:
df_y_hat2.shape

(16476, 1)

In [48]:
df_result.shape

(16476, 1)

In [49]:
df_result = df_result.join(df_y_hat2)

In [50]:
df_result.shape

(16476, 2)

In [51]:
df_result.head()

_id  target
0  66810d8e6bf2b41c880a7bc6c8a1e295       0
1  ccac3879652b08cb8b44c1920fd93afa       0
2  fcccab4d7a76f70647f015f2c84c2af8       0
3  ed8399278c30678dab739045fa12b440       0
4  1d4d62ac5cabcb48bac7112813f290cb       0

In [52]:
df_result.loc[:,'target'].value_counts()

0    15940
1      536
Name: target, dtype: int64

In [53]:
from sklearn.tree import DecisionTreeClassifier

In [60]:
tree_model = DecisionTreeClassifier(criterion='entropy', max_depth=5, random_state=123)

In [61]:
tree_model.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=5,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=123,
            splitter='best')

In [62]:
y_hat_tree = tree_model.predict(X_test)

In [63]:
y_hat_proba_tree = tree_model.predict_proba(X_test, )

In [64]:
y_hat_proba_tree[:20]

array([[0.99612088, 0.00387912],
       [0.99612088, 0.00387912],
       [0.81978799, 0.18021201],
       [0.88995215, 0.11004785],
       [0.51452282, 0.48547718],
       [0.88995215, 0.11004785],
       [0.99612088, 0.00387912],
       [0.97707231, 0.02292769],
       [0.26229508, 0.73770492],
       [0.99612088, 0.00387912],
       [0.15789474, 0.84210526],
       [0.99612088, 0.00387912],
       [0.97707231, 0.02292769],
       [0.99612088, 0.00387912],
       [0.99612088, 0.00387912],
       [0.99612088, 0.00387912],
       [0.32      , 0.68      ],
       [0.99612088, 0.00387912],
       [0.99612088, 0.00387912],
       [0.99612088, 0.00387912]])

In [65]:
roc_auc_score(y_test, y_hat_proba_tree[:, 1])

0.9194480058527822

In [66]:
y_hat3 = tree_model.predict(df_test)

In [67]:
y_hat_proba3 = tree_model.predict_proba(df_test, )

In [68]:
df_result_tree = df_y_test.copy()

In [69]:
df_result_tree.shape

(16476, 1)

In [70]:
df_y_hat3 = pd.DataFrame(y_hat3, columns=['target'])

In [71]:
df_y_hat3.shape

(16476, 1)

In [72]:
df_result_tree = df_result_tree.join(df_y_hat3)

In [73]:
df_result_tree.head(30)

_id  target
0   66810d8e6bf2b41c880a7bc6c8a1e295       0
1   ccac3879652b08cb8b44c1920fd93afa       0
2   fcccab4d7a76f70647f015f2c84c2af8       0
3   ed8399278c30678dab739045fa12b440       0
4   1d4d62ac5cabcb48bac7112813f290cb       0
5   aba2dec4c5cab88824f36babd24b986f       0
6   06f318f1dd178e738f675bb88a5adb84       0
7   d5036f5956e42ee6207296238fc4bc1d       0
8   fe0cc8933698ad4046ff2b82f65756eb       0
9   70190122f4ebf196535e11b33eb95b81       0
10  8c2e044ac444afd4d0dea67eba0079c4       0
11  0d7db1117ed3606d7bbbb65d584b5c2f       0
12  aa3d1e4ba96323b5449a23cb54badc50       1
13  d312d9b1ffdab785a806490ca0450f7b       0
14  56da3f911d7cc5e8f47f2703b74bdc45       0
15  19afb1a10078e901994a1e1e2c058652       0
16  9ac0fc025e2f551a7d5214a606a77434       0
17  4bc819b6f4ebbedca0fe354ba5dc7ba3       0
18  1c02af75529cdaee5f8822a5251f5c63       0
19  9d0424c7a80ebde8cc8b5520721592f2       0
20  cf005d4bc86312d5f1032e08ef342e05       1
21  6abe7bc6263ac81d7f6764c6b0489703       0
22  b56ee107fc7abbabfa317f9209cbc5fd       0
23  2fd2f7790cd8d0c638d55f41b1f323a2       0
24  bd3b2a1af1abd0d48af835aa69848232       0
25  d50372645903431bd7ceb57bbf1cea06       0
26  8a11f5487e2e8a6e91d0ab1b6003b55e       0
27  ab96e787fdf0827bbebcf95b1243d041       0
28  233d244d79e364f517c846cb3ab1932a       0
29  45971d4e3a47775bb5a7260bb5ea3c36       0

In [74]:
df_result_tree.loc[:,'target'].value_counts()

0    15213
1     1263
Name: target, dtype: int64

In [75]:
from sklearn.linear_model import LogisticRegression

In [77]:
logreg_model = LogisticRegression(C=1.0,
                           fit_intercept=True, 
                           penalty='l1')

In [78]:
logreg_model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [79]:
y_hat_logreg = logreg_model.predict(X_test)

In [80]:
y_hat_proba_logreg = logreg_model.predict_proba(X_test, )

In [81]:
roc_auc_score(y_test, y_hat_proba_logreg[:, 1])

0.9317051660944268

In [82]:
y_hat4 = tree_model.predict(df_test)

In [83]:
y_hat_proba4 = tree_model.predict_proba(df_test, )

In [84]:
df_result_logreg = df_y_test.copy()

In [85]:
df_result_logreg.shape

(16476, 1)

In [86]:
df_y_hat4 = pd.DataFrame(y_hat4, columns=['target'])

In [87]:
df_y_hat4.shape

(16476, 1)

In [88]:
df_result_logreg = df_result_logreg.join(df_y_hat4)

In [89]:
df_result_logreg.head(30)

_id  target
0   66810d8e6bf2b41c880a7bc6c8a1e295       0
1   ccac3879652b08cb8b44c1920fd93afa       0
2   fcccab4d7a76f70647f015f2c84c2af8       0
3   ed8399278c30678dab739045fa12b440       0
4   1d4d62ac5cabcb48bac7112813f290cb       0
5   aba2dec4c5cab88824f36babd24b986f       0
6   06f318f1dd178e738f675bb88a5adb84       0
7   d5036f5956e42ee6207296238fc4bc1d       0
8   fe0cc8933698ad4046ff2b82f65756eb       0
9   70190122f4ebf196535e11b33eb95b81       0
10  8c2e044ac444afd4d0dea67eba0079c4       0
11  0d7db1117ed3606d7bbbb65d584b5c2f       0
12  aa3d1e4ba96323b5449a23cb54badc50       1
13  d312d9b1ffdab785a806490ca0450f7b       0
14  56da3f911d7cc5e8f47f2703b74bdc45       0
15  19afb1a10078e901994a1e1e2c058652       0
16  9ac0fc025e2f551a7d5214a606a77434       0
17  4bc819b6f4ebbedca0fe354ba5dc7ba3       0
18  1c02af75529cdaee5f8822a5251f5c63       0
19  9d0424c7a80ebde8cc8b5520721592f2       0
20  cf005d4bc86312d5f1032e08ef342e05       1
21  6abe7bc6263ac81d7f6764c6b0489703       0
22  b56ee107fc7abbabfa317f9209cbc5fd       0
23  2fd2f7790cd8d0c638d55f41b1f323a2       0
24  bd3b2a1af1abd0d48af835aa69848232       0
25  d50372645903431bd7ceb57bbf1cea06       0
26  8a11f5487e2e8a6e91d0ab1b6003b55e       0
27  ab96e787fdf0827bbebcf95b1243d041       0
28  233d244d79e364f517c846cb3ab1932a       0
29  45971d4e3a47775bb5a7260bb5ea3c36       0

In [90]:
df_result_logreg.loc[:,'target'].value_counts()

0    15213
1     1263
Name: target, dtype: int64

In [91]:
df_result_logreg.to_csv('submission.csv', sep=',', encoding='utf-8', index=False)